
language: node_js
node_js:
  - "8"

sudo: required
services:
  - docker

cache: yarn

install:
  - yarn install

script:
  - yarn test
  - docker-compose up -d postgres
  - sleep 3
  - docker-compose up -d web
  - yarn cypress:run

